$(document).ready(function(){
    $("#hide").click(function(){
        $("h2").hide();
    });
    $("#show").click(function(){
        $("h2").show();
    });
});
$(document).ready(function(){
    $("#flip").click(function(){
        $("#panel").slideDown("slow");
    });
});